version: '3'
services:
    mysql56:
        image: 'mysql:5.6'
        command: --init-file /data/application/mysql.sql --default-authentication-plugin=mysql_native_password --sync_binlog=0 --innodb_doublewrite=OFF  --innodb-flush-log-at-trx-commit=0 --innodb-flush-method=nosync
        ports:
            - '5306:3306'
        environment:
            MYSQL_DATABASE: 'test_db'
            MYSQL_ROOT_PASSWORD: "root"
            MYSQL_USER: "lupdo"
            MYSQL_PASSWORD: "lupdo@s3cRet"
        healthcheck:
            test:
                [
                    'CMD',
                    '/usr/bin/mysql',
                    '-hlocalhost',
                    '-ulupdo',
                    '-plupdo@s3cRet',
                    '-e',
                    'SELECT 1'
                ]
            interval: 30s
            timeout: 5s
            retries: 3
        restart: always
        volumes:
            - ./src/__tests__/data/mysql.sql:/data/application/mysql.sql
    waitmysql56:
        image: 'mysql:5.6'
        links:
            - mysql56
        depends_on:
            - mysql56
        entrypoint:
            - bash
            - -c
            - 'until /usr/bin/mysql -hmysql56 -ulupdo -plupdo@s3cRet -e "SELECT 1"; do sleep 5; done'

    mysql57:
        image: 'mysql:5.7'
        command: --init-file /data/application/mysql.sql --default-authentication-plugin=mysql_native_password --sync_binlog=0 --innodb_doublewrite=OFF  --innodb-flush-log-at-trx-commit=0 --innodb-flush-method=nosync
        ports:
            - '5309:3306'
        environment:
            MYSQL_DATABASE: 'test_db'
            MYSQL_ROOT_PASSWORD: "root"
            MYSQL_USER: "lupdo"
            MYSQL_PASSWORD: "lupdo@s3cRet"
        healthcheck:
            test:
                [
                    'CMD',
                    '/usr/bin/mysql',
                    '-hlocalhost',
                    '-ulupdo',
                    '-plupdo@s3cRet',
                    '-e',
                    'SELECT 1'
                ]
            interval: 30s
            timeout: 5s
            retries: 3
        restart: always
        volumes:
            - ./src/__tests__/data/mysql.sql:/data/application/mysql.sql
    waitmysql57:
        image: 'mysql:5.7'
        links:
            - mysql57
        depends_on:
            - mysql57
        entrypoint:
            - bash
            - -c
            - 'until /usr/bin/mysql -hmysql57 -ulupdo -plupdo@s3cRet -e "SELECT 1"; do sleep 5; done'

    mysql8:
        image: 'mysql:8'
        command: --init-file /data/application/mysql.sql --default-authentication-plugin=mysql_native_password --sync_binlog=0 --innodb_doublewrite=OFF  --innodb-flush-log-at-trx-commit=0 --innodb-flush-method=nosync
        ports:
            - '5307:3306'
        environment:
            MYSQL_DATABASE: 'test_db'
            MYSQL_ROOT_PASSWORD: "root"
            MYSQL_USER: "lupdo"
            MYSQL_PASSWORD: "lupdo@s3cRet"
        healthcheck:
            test:
                [
                    'CMD',
                    '/usr/bin/mysql',
                    '-hlocalhost',
                    '-ulupdo',
                    '-plupdo@s3cRet',
                    '-e',
                    'SELECT 1'
                ]
            interval: 30s
            timeout: 5s
            retries: 3
        restart: always
        volumes:
            - ./src/__tests__/data/mysql.sql:/data/application/mysql.sql

    waitmysql8:
        image: 'mysql:8'
        links:
            - mysql8
        depends_on:
            - mysql8
        entrypoint:
            - bash
            - -c
            - 'until /usr/bin/mysql -hmysql8 -ulupdo -plupdo@s3cRet -e "SELECT 1"; do sleep 5; done'

    mariadb1003:
        image: 'mariadb:10.3'
        command: --init-file /data/application/mysql.sql --default-authentication-plugin=mysql_native_password --sync_binlog=0 --innodb_doublewrite=OFF  --innodb-flush-log-at-trx-commit=0 --innodb-flush-method=nosync
        ports:
            - '31003:3306'
        environment:
            MYSQL_DATABASE: 'test_db'
            MYSQL_ROOT_PASSWORD: "root"
            MYSQL_USER: "lupdo"
            MYSQL_PASSWORD: "lupdo@s3cRet"
        healthcheck:
            test:
                [
                    'CMD',
                    '/usr/bin/mysql',
                    '-hlocalhost',
                    '-ulupdo',
                    '-plupdo@s3cRet',
                    '-e',
                    'SELECT 1'
                ]
            interval: 30s
            timeout: 5s
            retries: 3
        restart: always
        volumes:
            - ./src/__tests__/data/mysql.sql:/data/application/mysql.sql

    waitmariadb1003:
        image: 'mariadb:10.3'
        links:
            - mariadb1003
        depends_on:
            - mariadb1003
        entrypoint:
            - bash
            - -c
            - 'until /usr/bin/mysql -hmariadb1003 -ulupdo -plupdo@s3cRet -e "SELECT 1"; do sleep 5; done'

    mariadb1004:
        image: 'mariadb:10.4'
        command: --init-file /data/application/mysql.sql --default-authentication-plugin=mysql_native_password --sync_binlog=0 --innodb_doublewrite=OFF  --innodb-flush-log-at-trx-commit=0 --innodb-flush-method=nosync
        ports:
            - '31004:3306'
        environment:
            MYSQL_DATABASE: 'test_db'
            MYSQL_ROOT_PASSWORD: "root"
            MYSQL_USER: "lupdo"
            MYSQL_PASSWORD: "lupdo@s3cRet"
        healthcheck:
            test:
                [
                    'CMD',
                    '/usr/bin/mysql',
                    '-hlocalhost',
                    '-ulupdo',
                    '-plupdo@s3cRet',
                    '-e',
                    'SELECT 1'
                ]
            interval: 30s
            timeout: 5s
            retries: 3
        restart: always
        volumes:
            - ./src/__tests__/data/mysql.sql:/data/application/mysql.sql

    waitmariadb1004:
        image: 'mariadb:10.4'
        links:
            - mariadb1004
        depends_on:
            - mariadb1004
        entrypoint:
            - bash
            - -c
            - 'until /usr/bin/mysql -hmariadb1004 -ulupdo -plupdo@s3cRet -e "SELECT 1"; do sleep 5; done'

    mariadb1005:
        image: 'mariadb:10.5'
        command: --init-file /data/application/mysql.sql --default-authentication-plugin=mysql_native_password --sync_binlog=0 --innodb_doublewrite=OFF  --innodb-flush-log-at-trx-commit=0 --innodb-flush-method=nosync
        ports:
            - '31005:3306'
        environment:
            MYSQL_DATABASE: 'test_db'
            MYSQL_ROOT_PASSWORD: "root"
            MYSQL_USER: "lupdo"
            MYSQL_PASSWORD: "lupdo@s3cRet"
        healthcheck:
            test:
                [
                    'CMD',
                    '/usr/bin/mysql',
                    '-hlocalhost',
                    '-ulupdo',
                    '-plupdo@s3cRet',
                    '-e',
                    'SELECT 1'
                ]
            interval: 30s
            timeout: 5s
            retries: 3
        restart: always
        volumes:
            - ./src/__tests__/data/mysql.sql:/data/application/mysql.sql

    waitmariadb1005:
        image: 'mariadb:10.5'
        links:
            - mariadb1005
        depends_on:
            - mariadb1005
        entrypoint:
            - bash
            - -c
            - 'until /usr/bin/mysql -hmariadb1005 -ulupdo -plupdo@s3cRet -e "SELECT 1"; do sleep 5; done'
    
    mariadb1006:
        image: 'mariadb:10.6'
        command: --init-file /data/application/mysql.sql --default-authentication-plugin=mysql_native_password --sync_binlog=0 --innodb_doublewrite=OFF  --innodb-flush-log-at-trx-commit=0 --innodb-flush-method=nosync
        ports:
            - '31006:3306'
        environment:
            MYSQL_DATABASE: 'test_db'
            MYSQL_ROOT_PASSWORD: "root"
            MYSQL_USER: "lupdo"
            MYSQL_PASSWORD: "lupdo@s3cRet"
        healthcheck:
            test:
                [
                    'CMD',
                    '/usr/bin/mysql',
                    '-hlocalhost',
                    '-ulupdo',
                    '-plupdo@s3cRet',
                    '-e',
                    'SELECT 1'
                ]
            interval: 30s
            timeout: 5s
            retries: 3
        restart: always
        volumes:
            - ./src/__tests__/data/mysql.sql:/data/application/mysql.sql

    waitmariadb1006:
        image: 'mariadb:10.6'
        links:
            - mariadb1006
        depends_on:
            - mariadb1006
        entrypoint:
            - bash
            - -c
            - 'until /usr/bin/mysql -hmariadb1006 -ulupdo -plupdo@s3cRet -e "SELECT 1"; do sleep 5; done'

    mariadb1007:
        image: 'mariadb:10.7'
        command: --init-file /data/application/mysql.sql --default-authentication-plugin=mysql_native_password --sync_binlog=0 --innodb_doublewrite=OFF  --innodb-flush-log-at-trx-commit=0 --innodb-flush-method=nosync
        ports:
            - '31007:3306'
        environment:
            MYSQL_DATABASE: 'test_db'
            MYSQL_ROOT_PASSWORD: "root"
            MYSQL_USER: "lupdo"
            MYSQL_PASSWORD: "lupdo@s3cRet"
        healthcheck:
            test:
                [
                    'CMD',
                    '/usr/bin/mysql',
                    '-hlocalhost',
                    '-ulupdo',
                    '-plupdo@s3cRet',
                    '-e',
                    'SELECT 1'
                ]
            interval: 30s
            timeout: 5s
            retries: 3
        restart: always
        volumes:
            - ./src/__tests__/data/mysql.sql:/data/application/mysql.sql

    waitmariadb1007:
        image: 'mariadb:10.7'
        links:
            - mariadb1007
        depends_on:
            - mariadb1007
        entrypoint:
            - bash
            - -c
            - 'until /usr/bin/mysql -hmariadb1007 -ulupdo -plupdo@s3cRet -e "SELECT 1"; do sleep 5; done'
    
    mariadb1008:
        image: 'mariadb:10.8'
        command: --init-file /data/application/mysql.sql --default-authentication-plugin=mysql_native_password --sync_binlog=0 --innodb_doublewrite=OFF  --innodb-flush-log-at-trx-commit=0 --innodb-flush-method=nosync
        ports:
            - '31008:3306'
        environment:
            MYSQL_DATABASE: 'test_db'
            MYSQL_ROOT_PASSWORD: "root"
            MYSQL_USER: "lupdo"
            MYSQL_PASSWORD: "lupdo@s3cRet"
        healthcheck:
            test:
                [
                    'CMD',
                    '/usr/bin/mysql',
                    '-hlocalhost',
                    '-ulupdo',
                    '-plupdo@s3cRet',
                    '-e',
                    'SELECT 1'
                ]
            interval: 30s
            timeout: 5s
            retries: 3
        restart: always
        volumes:
            - ./src/__tests__/data/mysql.sql:/data/application/mysql.sql

    waitmariadb1008:
        image: 'mariadb:10.8'
        links:
            - mariadb1008
        depends_on:
            - mariadb1008
        entrypoint:
            - bash
            - -c
            - 'until /usr/bin/mysql -hmariadb1008 -ulupdo -plupdo@s3cRet -e "SELECT 1"; do sleep 5; done'
    
    mariadb1009:
        image: 'mariadb:10.9'
        command: --init-file /data/application/mysql.sql --default-authentication-plugin=mysql_native_password --sync_binlog=0 --innodb_doublewrite=OFF  --innodb-flush-log-at-trx-commit=0 --innodb-flush-method=nosync
        ports:
            - '31009:3306'
        environment:
            MYSQL_DATABASE: 'test_db'
            MYSQL_ROOT_PASSWORD: "root"
            MYSQL_USER: "lupdo"
            MYSQL_PASSWORD: "lupdo@s3cRet"
        healthcheck:
            test:
                [
                    'CMD',
                    '/usr/bin/mysql',
                    '-hlocalhost',
                    '-ulupdo',
                    '-plupdo@s3cRet',
                    '-e',
                    'SELECT 1'
                ]
            interval: 30s
            timeout: 5s
            retries: 3
        restart: always
        volumes:
            - ./src/__tests__/data/mysql.sql:/data/application/mysql.sql

    waitmariadb1009:
        image: 'mariadb:10.9'
        links:
            - mariadb1009
        depends_on:
            - mariadb1009
        entrypoint:
            - bash
            - -c
            - 'until /usr/bin/mysql -hmariadb1009 -ulupdo -plupdo@s3cRet -e "SELECT 1"; do sleep 5; done'

    mariadb1010:
        image: 'mariadb:10.10'
        command: --init-file /data/application/mysql.sql --default-authentication-plugin=mysql_native_password --sync_binlog=0 --innodb_doublewrite=OFF  --innodb-flush-log-at-trx-commit=0 --innodb-flush-method=nosync
        ports:
            - '31010:3306'
        environment:
            MYSQL_DATABASE: 'test_db'
            MYSQL_ROOT_PASSWORD: "root"
            MYSQL_USER: "lupdo"
            MYSQL_PASSWORD: "lupdo@s3cRet"
        healthcheck:
            test:
                [
                    'CMD',
                    '/usr/bin/mysql',
                    '-hlocalhost',
                    '-ulupdo',
                    '-plupdo@s3cRet',
                    '-e',
                    'SELECT 1'
                ]
            interval: 30s
            timeout: 5s
            retries: 3
        restart: always
        volumes:
            - ./src/__tests__/data/mysql.sql:/data/application/mysql.sql

    waitmariadb1010:
        image: 'mariadb:10.10'
        links:
            - mariadb1010
        depends_on:
            - mariadb1010
        entrypoint:
            - bash
            - -c
            - 'until /usr/bin/mysql -hmariadb1010 -ulupdo -plupdo@s3cRet -e "SELECT 1"; do sleep 5; done'

    mariadb1011:
        image: 'mariadb:10.11-rc'
        command: --init-file /data/application/mysql.sql --default-authentication-plugin=mysql_native_password --sync_binlog=0 --innodb_doublewrite=OFF  --innodb-flush-log-at-trx-commit=0 --innodb-flush-method=nosync
        ports:
            - '31011:3306'
        environment:
            MYSQL_DATABASE: 'test_db'
            MYSQL_ROOT_PASSWORD: "root"
            MYSQL_USER: "lupdo"
            MYSQL_PASSWORD: "lupdo@s3cRet"
        healthcheck:
            test:
                [
                    'CMD',
                    '/usr/bin/mysql',
                    '-hlocalhost',
                    '-ulupdo',
                    '-plupdo@s3cRet',
                    '-e',
                    'SELECT 1'
                ]
            interval: 30s
            timeout: 5s
            retries: 3
        restart: always
        volumes:
            - ./src/__tests__/data/mysql.sql:/data/application/mysql.sql

    waitmariadb1011:
        image: 'mariadb:10.11-rc'
        links:
            - mariadb1011
        depends_on:
            - mariadb1011
        entrypoint:
            - bash
            - -c
            - 'until /usr/bin/mysql -hmariadb1011 -ulupdo -plupdo@s3cRet -e "SELECT 1"; do sleep 5; done'