version: '3'
services:
    mysql56:
        image: 'mysql:5.6'
        command: --init-file /data/application/mysql.sql --default-authentication-plugin=mysql_native_password --sync_binlog=0 --innodb_doublewrite=OFF  --innodb-flush-log-at-trx-commit=0 --innodb-flush-method=nosync
        ports:
            - '5306:3306'
        environment:
            MYSQL_DATABASE: 'test_db'
            MYSQL_ROOT_PASSWORD: "root"
            MYSQL_USER: "lupdo"
            MYSQL_PASSWORD: "lupdo@s3cRet"
        healthcheck:
            test:
                [
                    'CMD',
                    '/usr/bin/mysql',
                    '-hlocalhost',
                    '-ulupdo',
                    '-plupdo@s3cRet',
                    '-e',
                    'SELECT 1'
                ]
            interval: 30s
            timeout: 5s
            retries: 3
        restart: always
        volumes:
            - 'lupdo-mysql56:/var/lib/mysql'
            - ./src/__tests__/data/mysql.sql:/data/application/mysql.sql
    waitmysql56:
        image: 'mysql:5.6'
        links:
            - mysql56
        depends_on:
            - mysql56
        entrypoint:
            - bash
            - -c
            - 'until /usr/bin/mysql -hmysql56 -ulupdo -plupdo@s3cRet -e "SELECT 1"; do sleep 5; done'

    mysql57:
        image: 'mysql:5.7'
        command: --init-file /data/application/mysql.sql --default-authentication-plugin=mysql_native_password --sync_binlog=0 --innodb_doublewrite=OFF  --innodb-flush-log-at-trx-commit=0 --innodb-flush-method=nosync
        ports:
            - '5309:3306'
        environment:
            MYSQL_DATABASE: 'test_db'
            MYSQL_ROOT_PASSWORD: "root"
            MYSQL_USER: "lupdo"
            MYSQL_PASSWORD: "lupdo@s3cRet"
        healthcheck:
            test:
                [
                    'CMD',
                    '/usr/bin/mysql',
                    '-hlocalhost',
                    '-ulupdo',
                    '-plupdo@s3cRet',
                    '-e',
                    'SELECT 1'
                ]
            interval: 30s
            timeout: 5s
            retries: 3
        restart: always
        volumes:
            - 'lupdo-mysql57:/var/lib/mysql'
            - ./src/__tests__/data/mysql.sql:/data/application/mysql.sql
    waitmysql57:
        image: 'mysql:5.7'
        links:
            - mysql57
        depends_on:
            - mysql57
        entrypoint:
            - bash
            - -c
            - 'until /usr/bin/mysql -hmysql57 -ulupdo -plupdo@s3cRet -e "SELECT 1"; do sleep 5; done'

    mysql8:
        image: 'mysql:8'
        command: --init-file /data/application/mysql.sql --default-authentication-plugin=mysql_native_password --sync_binlog=0 --innodb_doublewrite=OFF  --innodb-flush-log-at-trx-commit=0 --innodb-flush-method=nosync
        ports:
            - '5307:3306'
        environment:
            MYSQL_DATABASE: 'test_db'
            MYSQL_ROOT_PASSWORD: "root"
            MYSQL_USER: "lupdo"
            MYSQL_PASSWORD: "lupdo@s3cRet"
        healthcheck:
            test:
                [
                    'CMD',
                    '/usr/bin/mysql',
                    '-hlocalhost',
                    '-ulupdo',
                    '-plupdo@s3cRet',
                    '-e',
                    'SELECT 1'
                ]
            interval: 30s
            timeout: 5s
            retries: 3
        restart: always
        volumes:
            - 'lupdo-mysql8:/var/lib/mysql'
            - ./src/__tests__/data/mysql.sql:/data/application/mysql.sql

    waitmysql8:
        image: 'mysql:8'
        links:
            - mysql8
        depends_on:
            - mysql8
        entrypoint:
            - bash
            - -c
            - 'until /usr/bin/mysql -hmysql8 -ulupdo -plupdo@s3cRet -e "SELECT 1"; do sleep 5; done'

    mariadb:
        image: 'mariadb:10'
        command: --init-file /data/application/mysql.sql --default-authentication-plugin=mysql_native_password --sync_binlog=0 --innodb_doublewrite=OFF  --innodb-flush-log-at-trx-commit=0 --innodb-flush-method=nosync
        ports:
            - '5308:3306'
        environment:
            MYSQL_DATABASE: 'test_db'
            MYSQL_ROOT_PASSWORD: "root"
            MYSQL_USER: "lupdo"
            MYSQL_PASSWORD: "lupdo@s3cRet"
        healthcheck:
            test:
                [
                    'CMD',
                    '/usr/bin/mysql',
                    '-hlocalhost',
                    '-ulupdo',
                    '-plupdo@s3cRet',
                    '-e',
                    'SELECT 1'
                ]
            interval: 30s
            timeout: 5s
            retries: 3
        restart: always
        volumes:
            - 'lupdo-mariadb:/var/lib/mysql'
            - ./src/__tests__/data/mysql.sql:/data/application/mysql.sql

    waitmariadb:
        image: 'mariadb:10'
        links:
            - mariadb
        depends_on:
            - mariadb
        entrypoint:
            - bash
            - -c
            - 'until /usr/bin/mysql -hmariadb -ulupdo -plupdo@s3cRet -e "SELECT 1"; do sleep 5; done'

volumes:
    lupdo-mysql56:
        driver_opts:
            type: tmpfs
            device: tmpfs
    lupdo-mysql57:
        driver_opts:
            type: tmpfs
            device: tmpfs
    lupdo-mysql8:
        driver_opts:
            type: tmpfs
            device: tmpfs
    lupdo-mariadb:
        driver_opts:
            type: tmpfs
            device: tmpfs
